name: nvim JSON

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: "nixpkgs=channel:nixos-23.05"

      - name: Build nvimJSON
        run: nix build .#nvimAttributes

      - name: Upload nvimJSON
        uses: actions/upload-artifact@v3
        with:
          name: nvimJSON
          path: ./result  # this assumes that the result symlink points to the nvimJSON output

